import Header from "@/Components/Header/Header";
import Navigator from "@/Components/Navigator/Navigator";
import "../styles/globals.scss";
import RootProviders from "./RootProviders";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <RootProviders>
      <html lang="en">
        <body>
          <Header />
          <Navigator />
          {children}
        </body>
      </html>
    </RootProviders>
  );
}
