import Header from "@/Components/Header/Header";
import Navigator from "@/Components/Navigator/Navigator";
import "../Styles/globals.scss";
import RootProviders from "./RootProviders";

export const metadata = {
  title: "Backgammon | Play",
  description: "Generated by create next app",
  icons: {
    icon: {
      url: "/Images/Favicon/icon.png",
      type: "image/png",
    },
  },
};

export default function RootLayout({ children }) {
  return (
    <RootProviders>
      <html lang="en">
        <body>
          <Header />

          <div className="container">
            <Navigator />
            {children}
          </div>
        </body>
      </html>
    </RootProviders>
  );
}
