import BackgammonGame from "@/Components/BackgammonGame/BackgammonGame";
import Header from "@/Components/Header/Header";
import Navigator from "@/Components/Navigator/Navigator";
import "../styles/globals.scss";
import RootProviders from "./RootProviders";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <RootProviders>
      <html lang="en">
        <body>
          <Header />

          <div className="container">
            <Navigator />
          </div>

          {children}

          <div className="container">
            <BackgammonGame />
          </div>
        </body>
      </html>
    </RootProviders>
  );
}
